name: StarLegacy
version: VersionsTakeEffort
main: net.starlegacy.StarLegacy
loadbefore: [Essentials]
depend: [StarLegacyLibs, LuckPerms, Vault, dynmap, WorldEdit, WorldGuard, Citizens, ProtocolLib]
softdepend: [GameAPI, GriefDefender]
api-version: "1.16"
